[package]
name = "y2015_d1"
version = "0.1.0"
authors = ["Ragib Badaruddin <ragib@seekasia.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
